language: python
python:
- '3.7'
- '3.8'
install: pip install -r requirements.txt
script: python -m coverage run --source=tunepy2/ -m unittest discover test/
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: 5F7SLD3wtjU+Aus9bQuchX0YrwI1xE0sYuhgxvxmTqet3V6tzFQukuDFr3yeEQohEvQNNzmty+q4ISy24GMnlNrJ3Uov5j5o4tpS+hfDVxcUl3L69KZzp2FEX5F1YDvF5txF5qEAtlV5wcLL/gMt9qBFjifmfPOHcM/QNbap4IbtA94XS4XvxDZBvWFNerGa9r1FpuOMHggONAKHhiyM6SkK/ca/JPiBIfh51czRn2s1tptUxo4aUYOgp1dTrPvJIT6FSvoW6gH7RnJ+QruoeJ/KPNrXGRFlHiToN0gLzTEKuqKLevDK2vkbdO9Uc88/xT1KBx/o/8pLTxmfv0fIfboCuWuVSSDf4aFbi4/Hoox8pUCRZIDn5vG25SDtwpPWHKUlyvBsFzts1AKHNlMzI8860XXxGc7DtoSbYuBHWfRChgCotbiOhOZav9WYKInOh4Q8FI5JcJ0u5Rivu6XJ+kKmmRpeljNibdD4HLr8VwbCDOsZwVLGfT33wdGnbyv2oAATa7OlH1485X8/FdXjkRdIzg8+xQNJkNeNsH9Ib2ek8kiUrpEWYJVQDaNpLlN3lXCBHXMpPIeB81BUoqq/Zm+Tbi9zZ5fFT+2BR3VPFMpMj3VB0N1fGxVULZn8UzwfAADxgzx9m8HTHOdf4Nj68q2aMchUXrjQDDQDlSL6yVs=
  skip_existing: true
  on:
    tags: true
