language: python
python:
- '3.7'
- '3.8'
install: pip install -r requirements.txt
script: python -m coverage run --source=tunepy2/ -m unittest discover test/
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: UW3fUNOzy4d1eWryVnFJTktn2J8OeYL9BOMBCL3zMswHdZoXhpHZHo8g4H9rQ5bQwRwWlej4Nes7SalBP8L2FP8fJYSlZ7abju1GllCuQkaPzpoe/SEP8JgdDwxz75JEPt1S0KAu3GVfwtoQbYv+CnDj9OITOu/CZ6PUfbKWRBx+DN4UZORjFGgNhWcdhnC/dXjNVA/ueHJVDBFn2WM5IfdGqxbMWHhkHZhov1wH1CN/QavGr5JIiFppdCo+6iae/ICqe50NVxKFSTcsFKMpkgVcSFMzPhm2EfsWTnSP8t6kAmPrh++vsiwpTxCIEruoT8tb9je+9Vjcyb60OKa6vIJ3fnp4rUT6Gza1SJKEhDzhylgnaLtyrTrTd3Rxq/FFNvL5959yqwy1w1RE4ohiCoO1SD1ho3FpLCq00gVGCD4FUWw0j+v3s1ZezdI22kC/SbhbI7xrSUtcIWFr4SVaTsfQG7tvo3C8fYjRH7r4vBaFZD7U7AHkLvNWRXHDdvLdH5pvotK3nbneY6Qlm8CeCYNpWgxRgq4horAdEfMIvgwsoplCWsDPqQmsjFT1aBhpr08WhtI/wIAiX1TMXJWKoWRAYA/+D+X6ohtbb1YQaxabY9HAc2VAsifZDa/FmZ284cSF/uQEzaVYyWXvR34dVY6qnNBCSY1ma5bIyJyKeK8=
